### PR TITLE
Fix #11: Switch to webpack (run npm install to get new deps)

### LINKED ISSUE #11: Switch to webpack
There are a whole bunch of errors people on Windows are having that I suspect are related to parceljs not working well in Windows with some shells.  I think I want to try switching over to using webpack 4.

Something like:

* https://www.valentinog.com/blog/webpack-4-tutorial/
* https://github.com/valentinogagliardi/webpack-4-quickstart

I love parceljs, but I need this to work for people on Windows by next week.

### PR DESCRIPTION
**Pull request by humphd**
This removes parceljs in favour of webpack4.  To test/use this, make sure you first run `npm install` to get the new dependencies.

A few things to note:

* The port has changed to `:8080` so open your page at `http://localhost:8080/`
* For people working on pulling in different SVG files, you can now just use `require('../path/to/file.svg')` and it will give you a Data URL automatically.  See changes in `src/svg-marker.js`

### CODE REVIEW

**Comment by irrationalRock** [comment]
I currently get this error when running your changes on cmd:
```
'webpack-dev-server' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bridge-troll@1.0.0 debug: `webpack-dev-server --mode development --define process.env.FAKE_GEO=1 --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bridge-troll@1.0.0 debug script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\irrat\AppData\Roaming\npm-cache\_logs\2018-03-16T13_47_22_926Z-debug.log
```
However, bash on windows works fine.

**Comment by humphd** [comment]
Asking some colleagues for advice on Twitter, I'll see what they say: https://twitter.com/humphd/status/974655988342120448

**Comment by humphd** [comment]
@irrationalRock can you confirm this for me?

> Yeah, that is absolutely something else, like a bad npm install. Check `npm config list` and see whether it's pointing to bad locations. Also make sure it's actually a recent version of npm, and not npm2 or something.

Which version of node and npm are you using?  Does `npm config list` show any badness? 

cc @Pomax

**Comment by humphd** [comment]
@irrationalRock also:

> Another possibility is that they ran npm install from WSL and it didn't install the correct windows stubs.

**Comment by irrationalRock** [comment]
when I did `npm config list` on cmd :
```
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/5.6.0 node/v9.4.0 win32 x64"

; builtin config undefined
prefix = "C:\\Users\\irrat\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\irrat\Documents\OSD600\lab5\bridge-troll
; HOME = C:\Users\irrat
; "npm config ls -l" to show all defaults.
```

and on windows bash:
```
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/5.6.0 node/v9.8.0 linux x64"

; node bin location = /usr/local/bin/node
; cwd = /mnt/c/Users/irrat/Documents/OSD600/lab5/bridge-troll
; HOME = /home/mgquan
; "npm config ls -l" to show all defaults.
```

It looks similar. @humphd  Is there something i'm missing?

**Comment by humphd** [comment]
The only thing I see is that the versions of node are different, but I think this is an `npm` issue.  I'm stumped.  Everyone says "this should work."  I'm tempted to go with my PR and then follow up with fixes as we find more.

**Comment by irrationalRock** [comment]
Let me try this on a different windows computer. I'll let you know if this is a one off with my computer.

**Comment by Pomax** [comment]
how were node and npm installed? With the normal installer from https://nodejs.org?

**Comment by irrationalRock** [comment]
Yes, I used the normal installer from https://nodejs.org.

The weird thing is that I have a nearly identical setup on another box and it works fine with cmd and windows bash.

I'm trying to narrow down what is causing this.

**Comment by Pomax** [comment]
You might be running into some weird linking-gone-wrong issue, I'd honestly file this on the npm issue tracker with most of the details uncovered here so far and see if anyone might know what's going on in parallel.

**Pull request merged**
